import { ArrowUpRight, Check, Clock3, Mail, MapPin, Menu, Phone, ShieldCheck, Wrench, Zap } from 'lucide-react';

const wa = 'https://wa.me/593979305325?text=Hola%20Digital%20Copy%2C%20quiero%20recibir%20informaci%C3%B3n%20sobre%20venta%2C%20alquiler%20o%20soporte%20t%C3%A9cnico%20de%20impresoras.';
const services = [
  ['01', 'Venta de equipos', 'Impresoras y multifuncionales para trabajar sin interrupciones.', 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=900&q=85'],
  ['02', 'Alquiler corporativo', 'Planes flexibles con equipos de alto rendimiento y respaldo.', 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=900&q=85'],
  ['03', 'Soporte técnico', 'Mantenimiento preventivo y correctivo con respuesta rápida.', 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=85'],
  ['04', 'Suministros', 'Tóneres, repuestos y consumibles originales o compatibles.', 'https://images.unsplash.com/photo-1629810688607-3e7e1b8e8f5f?auto=format&fit=crop&w=900&q=85'],
];
const brands = ['KONICA MINOLTA', 'RICOH', 'KYOCERA', 'CANON', 'HP', 'XEROX'];

export default function Home() {
  return <main><div className="progress" />
    <header className="nav"><a className="logo" href="#inicio"><span className="logo-mark">D</span><span>Digital <b>Copy</b><small>Tecnología que impulsa tu negocio</small></span></a><nav><a href="#servicios">Servicios</a><a href="#equipos">Equipos</a><a href="#marcas">Marcas</a><a href="#nosotros">Nosotros</a><a href="#contacto">Contacto</a></nav><a className="nav-cta" href={wa}>WhatsApp <ArrowUpRight size={15}/></a><Menu className="mobile-menu" /></header>
    <section id="inicio" className="hero"><div className="hero-copy"><p className="eyebrow"><span /> VENTA · ALQUILER · SOPORTE · SUMINISTROS</p><h1>Imprime mejor.<br/><em>Crece sin límites.</em></h1><p className="hero-text">Soluciones profesionales de impresión para empresas que necesitan eficiencia, continuidad y respaldo técnico.</p><div className="actions"><a className="button green" href={wa}>Cotiza por WhatsApp <ArrowUpRight size={18}/></a><a className="button ghost" href="tel:+593979305325">Llámanos <Phone size={17}/></a></div><div className="hero-stats"><span><strong>+15</strong> años de experiencia</span><span><strong>24h</strong> respuesta técnica</span></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=1400&q=90" alt="Impresora multifunción profesional en una oficina"/><div className="visual-tag"><span className="dot"/> Equipos listos para tu operación</div></div></section>
    <section className="trust"><div><ShieldCheck/><span><b>Equipos originales</b><small>Garantía y respaldo</small></span></div><div><Wrench/><span><b>Soporte especializado</b><small>Técnicos certificados</small></span></div><div><Zap/><span><b>Respuesta rápida</b><small>Atención cuando importa</small></span></div><div><Clock3/><span><b>Planes flexibles</b><small>Compra o alquiler</small></span></div></section>
    <section id="servicios" className="section"><div className="section-head"><div><p className="eyebrow dark"><span /> SOLUCIONES PARA TU EMPRESA</p><h2>Todo lo que necesitas<br/><em>para imprimir mejor.</em></h2></div><p>Un solo aliado para tus equipos, consumibles y soporte técnico. Diseñamos soluciones que se adaptan a tu ritmo.</p></div><div className="service-grid">{services.map(([n,t,d,img])=><article className="service" key={n}><div className="service-image"><img src={img} alt={t}/><span>{n}</span></div><div><h3>{t}</h3><p>{d}</p><a href={wa}>Conocer más <ArrowUpRight size={15}/></a></div></article>)}</div></section>
    <section id="equipos" className="dark-section"><div className="equipment-copy"><p className="eyebrow"><span /> EQUIPOS DE ALTO RENDIMIENTO</p><h2>La potencia que tu negocio <em>necesita.</em></h2><p>Multifuncionales diseñados para imprimir, copiar y escanear con velocidad, precisión y bajo costo operativo.</p><a className="button green" href={wa}>Cotizar equipo <ArrowUpRight size={18}/></a></div><div className="equipment-image"><img src="https://images.unsplash.com/photo-1563770660941-10a1a4b4e55b?auto=format&fit=crop&w=1200&q=85" alt="Equipo multifunción en entorno corporativo"/></div></section>
    <section id="marcas" className="brands"><p className="eyebrow dark"><span /> TECNOLOGÍA EN LA QUE CONFÍAS</p><h2>Las mejores marcas, <em>un solo lugar.</em></h2><div className="brand-row">{brands.map(b=><span key={b}>{b}</span>)}</div></section>
    <section id="nosotros" className="promise"><div><p className="eyebrow"><span /> TU OPERACIÓN, SIEMPRE ACTIVA</p><h2>Más que impresoras.<br/><em>Un respaldo real.</em></h2></div><div className="promise-list"><p><b>01</b><span><strong>Asesoría que entiende tu negocio</strong><small>Te ayudamos a elegir la solución correcta desde el primer día.</small></span></p><p><b>02</b><span><strong>Soporte cuando lo necesitas</strong><small>Mantenimiento, repuestos y atención cercana para no detenerte.</small></span></p><p><b>03</b><span><strong>Costos claros y controlados</strong><small>Planes de alquiler y suministros que cuidan tu presupuesto.</small></span></p></div></section>
    <section id="contacto" className="contact"><div><p className="eyebrow dark"><span /> HABLEMOS DE TU PROYECTO</p><h2>¿Listo para imprimir<br/><em>sin complicaciones?</em></h2><p>Cuéntanos qué necesitas. Nuestro equipo te responde con una recomendación clara y una cotización a tu medida.</p></div><div className="contact-card"><h3>Solicita tu cotización</h3><a className="button green" href={wa}>Escribir por WhatsApp <ArrowUpRight size={18}/></a><a className="phone-link" href="tel:+593979305325"><Phone size={16}/> 097 930 5325</a></div></section>
    <footer><div className="footer-top"><a className="logo" href="#inicio"><span className="logo-mark">D</span><span>Digital <b>Copy</b><small>Tecnología que impulsa tu negocio</small></span></a><div className="footer-info"><span><MapPin size={16}/> Av. 10 de Agosto y Rumipamba</span><span><Mail size={16}/> digitalcopy@gmail.com</span></div></div><div className="footer-bottom"><span>© 2025 Digital Copy. Todos los derechos reservados.</span><span>Lun–Vie 8:30–17:30 · Sáb 8:30–13:00</span></div></footer><a className="float-wa" href={wa} aria-label="Escribir por WhatsApp">◔</a>
  </main>;
}
